from pathlib import Path

def generate_html_report(domain, ip, response, findings,output_dir="results"):

    report = Path(output_dir) / domain / "report.html"

    html = f"""
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">

<title>BugHunter Toolkit Report</title>

<style>

body {{
    font-family: Arial, Helvetica, sans-serif;
    background:#f5f5f5;
    margin:40px;
}}

.banner {{

    background:#2c3e50;

    color:white;

    padding:25px;

    border-radius:10px;

    margin-bottom:30px;

}}

.banner h1{{

    margin:0;

}}

.banner p{{

    margin-top:8px;

    color:#d5d5d5;

}}

.banner h1 {{

    color:white;

    margin:0;

}}

.container {{
    background:white;
    padding:30px;
    border-radius:10px;
    box-shadow:0 0 10px rgba(0,0,0,.1);
}}

h1 {{
    color:#2c3e50;
}}

table {{
    width:100%;
    border-collapse:collapse;
    margin-top:20px;
}}

th, td {{
    border:1px solid #ddd;
    padding:12px;
}}

th {{
    background:#2c3e50;
    color:white;
}}

.good {{
    color:green;
    font-weight:bold;
}}

.bad {{
    color:red;
    font-weight:bold;
}}

footer {{
    margin-top:40px;
    color:gray;
}}

</style>

</head>

<body>

<div class="container">



<div class="banner">

<h1>BugHunter Toolkit Report</h1>

<p>Professional Web Reconnaissance Report</p>

</div>


<h2>Executive Summary</h2>

<table>

<tr>
<td><b>Target</b></td>
<td>{domain}</td>
</tr>

<tr>
<td><b>IP Address</b></td>
<td>{ip}</td>
</tr>

<tr>
<td><b>Final URL</b></td>
<td>{response.url}</td>
</tr>

<tr>
<td><b>Status Code</b></td>
<td>{response.status_code}</td>
</tr>

</table>


<h2>Security Headers</h2>

<table>

<tr>

<th>Header</th>

<th>Status</th>

</tr>
"""

    for item in findings:

        css = "good" if item["status"] == "Present" else "bad"

        html += f"""

<tr>

<td>{item["description"]}</td>

<td class="{css}">{item["status"]}</td>

</tr>

"""

    html += """

</table>

<footer>

Generated by BugHunter Toolkit

</footer>

</div>

</body>

</html>

"""

    report.write_text(html, encoding="utf-8")
