from pathlib import Path


def generate_html_report(
    domain,
    ip,
    response,
    findings,
    technologies,
    output_dir="results"
):
    report = Path(output_dir) / domain / "report.html"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BugHunter Toolkit Report</title>

<style>
body {{
    font-family: Arial, Helvetica, sans-serif;
    background: #f5f5f5;
    margin: 40px;
}}

.container {{
    background: white;
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0,0,0,.15);
}}

.banner {{
    background: #2c3e50;
    color: white;
    padding: 25px;
    border-radius: 10px;
    margin-bottom: 30px;
}}

.banner h1 {{
    margin: 0;
    color: white;
}}

.banner p {{
    margin-top: 8px;
    color: #dddddd;
}}

h2 {{
    color: #2c3e50;
    margin-top: 35px;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    margin-top: 15px;
}}

th, td {{
    border: 1px solid #dddddd;
    padding: 12px;
    text-align: left;
}}

th {{
    background: #2c3e50;
    color: white;
}}

.good {{
    color: green;
    font-weight: bold;
}}

.bad {{
    color: red;
    font-weight: bold;
}}

.tech {{
    background: #eef6ff;
    border-radius: 6px;
    padding: 6px 10px;
    display: inline-block;
}}

footer {{
    margin-top: 40px;
    color: gray;
    text-align: center;
}}
</style>

</head>

<body>

<div class="container">

<div class="banner">
<h1>BugHunter Toolkit Report</h1>
<p>Professional Web Reconnaissance Report</p>
</div>

<h2>Executive Summary</h2>

<table>
<tr>
<th>Field</th>
<th>Value</th>
</tr>

<tr>
<td>Target</td>
<td>{domain}</td>
</tr>

<tr>
<td>IP Address</td>
<td>{ip}</td>
</tr>

<tr>
<td>Final URL</td>
<td>{response.url}</td>
</tr>

<tr>
<td>Status Code</td>
<td>{response.status_code}</td>
</tr>

</table>

<h2>Security Headers</h2>

<table>

<tr>
<th>Header</th>
<th>Status</th>
</tr>
"""

    for item in findings:

        css = "good" if item["status"] == "Present" else "bad"

        html += f"""
<tr>
<td>{item["description"]}</td>
<td class="{css}">{item["status"]}</td>
</tr>
"""

    html += """
</table>

<h2>Technology Detection</h2>
"""

    if technologies:

        for tech in technologies:

            html += f"""
<p class="tech">{tech}</p>
"""

    else:

        html += """
<p>No technologies detected.</p>
"""

    html += """
<footer>

<hr>

Generated by <strong>BugHunter Toolkit</strong>

</footer>

</div>

</body>

</html>
"""

    report.write_text(html, encoding="utf-8")
