from pathlib import Path
from datetime import datetime


def generate_report(domain, ip, response):

    report = Path("results") / domain / "report.md"

    with open(report, "w", encoding="utf-8") as file:

        file.write("# BugHunter Toolkit Report\n\n")

        file.write("---\n\n")

        file.write("## Executive Summary\n\n")

        file.write(f"**Target:** {domain}\n\n")

        file.write(f"**Scan Time:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        file.write(f"**IP Address:** {ip}\n\n")

        if response:

            file.write(f"**Final URL:** {response.url}\n\n")

            file.write(f"**Status Code:** {response.status_code}\n\n")

            file.write("---\n\n")

            file.write("## Response Headers\n\n")

            for key, value in response.headers.items():

                file.write(f"- **{key}**: {value}\n")

            file.write("\n---\n\n")

            file.write("## Scan Summary\n\n")

            file.write("- HTTP connection established successfully.\n")
            file.write("- Response headers collected.\n")
            file.write("- robots.txt and sitemap.xml checked.\n")
            file.write("- Security headers analyzed.\n\n")

            file.write("---\n\n")

            file.write("Generated by **BugHunter Toolkit v1.1**\n")
